package icejawriter.install

import java.io.File

/**
 * Launcher scripts generated by the installer (УСТ-22.3): a POSIX shell
 * script for Linux/macOS and a Windows batch script. Both resolve the java
 * command from JAVA_HOME first (if it points to a working JVM) and fall back
 * to PATH.
 */
object LauncherScripts {

    /** Returns the launcher script content for the given OS family. */
    fun scriptFor(osKind: OsKind): String = when (osKind) {
        OsKind.LINUX, OsKind.MACOS -> shellScript()
        OsKind.WINDOWS -> batchScript()
    }

    /** POSIX shell launcher (Linux/macOS). */
    fun shellScript(): String {
        val separator = File.separator
        return buildString {
            appendLine("#!/bin/sh")
            appendLine("# IceJA Writer launcher (Linux/macOS).")
            appendLine("# Resolves java from JAVA_HOME first, then from PATH.")
            appendLine("if [ -n \"\${JAVA_HOME}\" ] && [ -x \"\${JAVA_HOME}${separator}bin${separator}java\" ]; then")
            appendLine("    JAVA_BIN=\"\${JAVA_HOME}${separator}bin${separator}java\"")
            appendLine("else")
            appendLine("    JAVA_BIN=\"java\"")
            appendLine("fi")
            appendLine("SCRIPT_DIR=\$(CDPATH= cd -P -- \"\$(dirname -- \"\$0\")\" && pwd -P)")
            append("exec \"\$JAVA_BIN\" -jar \"\$SCRIPT_DIR\"${separator}${InstallDefaults.JAR_FILE_NAME}\" \"\$@\"")
            append("\n")
        }
    }

    /** Windows batch launcher. */
    fun batchScript(): String = buildString {
        appendLine("@echo off")
        appendLine("rem IceJA Writer launcher (Windows).")
        appendLine("rem Resolves java from JAVA_HOME first, then from PATH.")
        appendLine("setlocal")
        appendLine("if defined JAVA_HOME (")
        appendLine("    set \"JAVA_BIN=%JAVA_HOME%\\bin\\java.exe\"")
        appendLine(") else (")
        appendLine("    set \"JAVA_BIN=java\"")
        appendLine(")")
        append("\"%JAVA_BIN%\" -jar \"%~dp0${InstallDefaults.JAR_FILE_NAME}\" %*")
        append("\n")
    }
}